import os
from building import *
import rtconfig

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

src     = []
CPPPATH = [cwd]

group = DefineGroup('mlibc', src, depend = [''], CPPPATH = CPPPATH)

objs += group
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
