from building import *
import os

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd + '/../include/']

group = DefineGroup('__mlibc_rtthread', src, depend = [''], CPPPATH = CPPPATH)

Return('group')